try:
    print(x)
except Exception as error:
    print(error)
finally:
    print("Teeeeste")
